version: "3"
services:
  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      
  react:
    container_name: frontend
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /usr/src/frontend/node_modules
      - /usr/src/frontend
    ports:
      - 3000:3000
    depends_on:
      - django
    