# Generated by Django 3.1.7 on 2022-02-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20220205_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='photo',
            new_name='image',
        ),
    ]
